// Generated by CoffeeScript 1.7.1
var DefaultTabletConfig, MongoClient, Server, fs, genBlindsActions, getBlindsActions, getDeviceConfigList, getDoorActions, getServerList, getSonosConfig, mongoUrl, replaceAll, replaceFavs, setConfigInDb, sonosServerUrl,
  __indexOf = [].indexOf || function(item) { for (var i = 0, l = this.length; i < l; i++) { if (i in this && this[i] === item) return i; } return -1; };

MongoClient = require('mongodb').MongoClient;

Server = require('mongodb').Server;

fs = require('fs');

DefaultTabletConfig = require('../www/js/default-tablet-config.js');

mongoUrl = 'mongodb://macallan:27017/WallTablets';

if (process.argv[2] != null) {
  if (process.argv[2] === "localhost") {
    mongoUrl = 'mongodb://localhost:27017/WallTablets';
  } else if (process.argv[2][0] !== '-') {
    mongoUrl = process.argv[2];
  }
}

console.log("Mongo database is " + mongoUrl);

replaceFavs = false;

if ((process.argv[2] != null) && process.argv[2] === "-replacefavs" || (process.argv[3] != null) && process.argv[3] === "-replacefavs") {
  replaceFavs = true;
}

sonosServerUrl = 'http://macallan:5005';

replaceAll = function(find, replace, str) {
  return str.replace(new RegExp(find, 'g'), replace);
};

console.log('Setting Tablet Configuration from folder');

console.log(__dirname + '/tablets');

console.log();

MongoClient.connect(mongoUrl, function(err, db) {
  var bAction, blindsActions, commonConfig, configSettingsToGet, configsToSet, dAction, defaultTabletConfig, devConf, deviceConfigList, doorActions, key, newConfig, sAction, sonosConfig, val, _i, _j, _k, _l, _len, _len1, _len2, _len3;
  if (!db) {
    console.error('Error! MongoDB must be running ... Shutting down');
    process.exit(1);
  }
  configsToSet = {
    count: 0
  };
  defaultTabletConfig = new DefaultTabletConfig();
  configSettingsToGet = {
    showCalServerButton: true,
    showEnergyServerButton: true,
    calServerUrl: "http://macallan:5077/calendar/min/45",
    energyServerUrl: "http://macallan:5098"
  };
  commonConfig = defaultTabletConfig.get(configSettingsToGet);
  deviceConfigList = getDeviceConfigList();
  doorActions = getDoorActions();
  sonosConfig = getSonosConfig(deviceConfigList);
  blindsActions = getBlindsActions();
  for (_i = 0, _len = doorActions.length; _i < _len; _i++) {
    dAction = doorActions[_i];
    commonConfig.common.fixedActions.push(dAction);
  }
  for (_j = 0, _len1 = blindsActions.length; _j < _len1; _j++) {
    bAction = blindsActions[_j];
    commonConfig.common.fixedActions.push(bAction);
  }
  for (_k = 0, _len2 = sonosConfig.length; _k < _len2; _k++) {
    sAction = sonosConfig[_k];
    commonConfig.common.fixedActions.push(sAction);
  }
  for (_l = 0, _len3 = deviceConfigList.length; _l < _len3; _l++) {
    devConf = deviceConfigList[_l];
    newConfig = {};
    for (key in devConf) {
      val = devConf[key];
      newConfig[key] = val;
    }
    newConfig["common"] = commonConfig.common;
    newConfig.common["servers"] = getServerList();
    setConfigInDb(db, newConfig, configsToSet, devConf.favourites);
  }
});

setConfigInDb = function(configDb, deviceConfig, configsToSet, favourites) {
  configDb.collection('TabletConfig').findOne({
    'deviceName': deviceConfig['deviceName']
  }, function(err, doc) {
    var curFavourites, fav, _i, _len, _ref;
    curFavourites = [];
    if ((!replaceFavs) && (doc != null) && (doc.favourites != null) && doc.favourites.length !== 0) {
      _ref = doc.favourites;
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        fav = _ref[_i];
        if (__indexOf.call(curFavourites, fav) < 0) {
          curFavourites.push(fav);
        }
      }
    }
    if (curFavourites.length > 0) {
      deviceConfig["favourites"] = curFavourites;
    }
    configsToSet.count++;
    configDb.collection('TabletConfig').update({
      'deviceName': deviceConfig['deviceName']
    }, deviceConfig, {
      upsert: true
    }, function(err, numberOfRemovedDocs) {
      if (err !== null) {
        console.log('Failed to save new info ' + err);
        configDb.close();
        process.exit(1);
      } else {
        configsToSet.count--;
        if (configsToSet.count === 0) {
          console.log('All config set');
          configDb.close();
          process.exit(1);
        }
      }
    });
  });
};

getSonosConfig = function(deviceConfigList) {
  var act, actionConfig, confIdx, deviceConfig, roomName, sonosConfig, sonosRoomName, _i, _j, _len, _len1;
  sonosConfig = [];
  for (confIdx = _i = 0, _len = deviceConfigList.length; _i < _len; confIdx = ++_i) {
    deviceConfig = deviceConfigList[confIdx];
    sonosRoomName = deviceConfig['sonosRoomName'];
    roomName = deviceConfig['roomName'];
    if (deviceConfig['sonosRoomName'] === '') {
      confIdx++;
      continue;
    }
    actionConfig = [
      {
        'actionName': 'Play',
        'iconName': 'music-play',
        'uri': '/play'
      }, {
        'actionName': 'Stop',
        'iconName': 'music-stop',
        'uri': '/pause'
      }, {
        'actionName': 'Vol +',
        'iconName': 'music-vol-up',
        'uri': '/volume/+10'
      }, {
        'actionName': 'Vol -',
        'iconName': 'music-vol-down',
        'uri': '/volume/-10'
      }
    ];
    for (_j = 0, _len1 = actionConfig.length; _j < _len1; _j++) {
      act = actionConfig[_j];
      act['actionUrl'] = sonosServerUrl + '/' + sonosRoomName + act['uri'];
      act['uri'] = sonosServerUrl + '/' + sonosRoomName + act['uri'];
      act['groupName'] = roomName;
      act['tierName'] = 'sonosTier';
      act['colSpan'] = 1;
      act['rowSpan'] = 1;
      act['name'] = act['actionName'];
      act['visibility'] = 'all';
      act['tileType'] = 'Sonos';
      sonosConfig.push(act);
    }
    confIdx++;
  }
  return sonosConfig;
};

getBlindsActions = function() {
  var blindsDef;
  blindsDef = [["Games", [["1", "Shade 1"], ["2", "Shade 2"]], "http://192.168.0.225/blind/"], ["Landing Bath", [["1", "Shade"]], "http://192.168.0.226/blind/"], ["Office", [["1", "Rob's Shade"], ["2", "Left"], ["3", "Mid-Left"], ["4", "Mid-Right"], ["5", "Right"]], "http://192.168.0.220/blind/"]];
  return genBlindsActions(blindsDef);
};

genBlindsActions = function(blindsDefs) {
  var actions, blindsDirns, dirn, room, win, _i, _j, _k, _len, _len1, _len2, _ref;
  blindsDirns = [["Up", "up"], ["Stop", "stop"], ["Down", "down"]];
  actions = [];
  for (_i = 0, _len = blindsDefs.length; _i < _len; _i++) {
    room = blindsDefs[_i];
    for (_j = 0, _len1 = blindsDirns.length; _j < _len1; _j++) {
      dirn = blindsDirns[_j];
      _ref = room[1];
      for (_k = 0, _len2 = _ref.length; _k < _len2; _k++) {
        win = _ref[_k];
        actions.push({
          tierName: "doorBlindsTier",
          actionNum: 0,
          actionName: win[1] + " " + dirn[0],
          groupName: room[0],
          actionUrl: room[2] + win[0] + "/" + dirn[1] + "/pulse",
          iconName: "blinds-" + dirn[1]
        });
      }
    }
  }
  return actions;
};

getDoorActions = function() {
  return [
    {
      actionName: "Main Unlock",
      groupName: "Front Door",
      actionUrl: "http://192.168.0.221/main-unlock",
      iconName: "door-unlock"
    }, {
      actionName: "Main Lock",
      groupName: "Front Door",
      actionUrl: "http://192.168.0.221/main-lock",
      iconName: "door-lock"
    }, {
      actionName: "Inner Unlock",
      groupName: "Front Door",
      actionUrl: "http://192.168.0.221/inner-unlock",
      iconName: "door-unlock"
    }, {
      actionName: "Inner Lock",
      groupName: "Front Door",
      actionUrl: "http://192.168.0.221/inner-lock",
      iconName: "door-lock"
    }
  ];
};

getDeviceConfigList = function(configDb) {
  var baseFolder, devInfo, deviceInfoList, fIdx, folderList, jsonStr;
  deviceInfoList = [];
  baseFolder = './tablets/';
  folderList = fs.readdirSync(baseFolder);
  fIdx = 0;
  while (fIdx < folderList.length) {
    if (folderList[fIdx].indexOf('.json') > 0) {
      jsonStr = fs.readFileSync(baseFolder + folderList[fIdx], {
        encoding: 'utf8'
      });
      jsonStr = replaceAll('@sonosServerUrl', sonosServerUrl, jsonStr);
      devInfo = JSON.parse(jsonStr);
      deviceInfoList.push(devInfo);
    }
    fIdx++;
  }
  return deviceInfoList;
};

getServerList = function() {
  return [
    {
      "type": "domoticz",
      "name": "DomoticzUT",
      "url": "http://192.168.0.232:80",
      "iconAliasing": "automationIcons"
    }, {
      "type": "domoticz",
      "name": "DomoticzPLC",
      "url": "http://192.168.0.233:80",
      "iconAliasing": "automationIcons"
    }, {
      "type": "domoticz",
      "name": "DomoticzCEL",
      "url": "http://192.168.0.234:80",
      "iconAliasing": "automationIcons"
    }, {
      "type": "domoticz",
      "name": "DomoticzOFF",
      "url": "http://192.168.0.235:80",
      "iconAliasing": "automationIcons"
    }, {
      "type": "domoticz",
      "name": "DomoticzKIT",
      "url": "http://192.168.0.236:80",
      "iconAliasing": "automationIcons"
    }
  ];
};
